# Generated by Django 6.0.2 on 2026-03-04 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_rename_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='learning_le_subskil_98add6_idx',
        ),
        migrations.RemoveIndex(
            model_name='module',
            name='learning_su_skill_i_51876e_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='learning_co_slug_b348c5_idx',
            old_name='learning_sk_slug_605f10_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='learning_le_module__83c7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='learning_mo_course__7897c1_idx'),
        ),
    ]
