# Generated by Django 6.0.2 on 2026-03-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_remove_lesson_learning_le_subskil_98add6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='last_play_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
